server:
  port: 9501
cdn_protocol: http
mysql:
  web:
    host: 127.0.0.1
    username: root
    password: root
    dbname: db_web
    port: 3306
mongodb:
  host: 127.0.0.1
  port: 3717
  username: root
  password: root
elasticsearch:
  host: 127.0.0.1
  auth: root
  password: root
  port: 9200
redis:
  host: 127.0.0.1
  port: 6379
  database: 2
  password: root
oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  access_key_id: root
  access_key_secret: root
  bucket: img
  salt: root
mns:
  url: http://mns.cn-shanghai.aliyuncs.com
  access_key_id: root
  access_key_secret: root